{ config, pkgs, lib, root, ... }:

let
  discordPkg    = pkgs.discord.override { withVencord = true; };
  wallSrc       = "${root}/files/wallpapers/discord-wallpaper.jpg";
  destDir       = ".config/Vencord/themes";
  themeName     = "default-nature-tokyo.theme.css";
  cssLines = lib.concatStringsSep "\n" [
    "/**"
    " * @name Default nature tokyo night theme"
    " * @version 7.0.1"
    " */"
    "@import url(\"https://clearvision.github.io/ClearVision-v7/main.css\");"
    "@import url(\"https://clearvision.github.io/ClearVision-v7/betterdiscord.css\");"
    ":root {"
    "  --main-color: #2780e6;"
    "  --hover-color: #1e63b3;"
    "  --success-color: #43b581;"
    "  --danger-color: #982929;"
    "  --online-color: #43b581;"
    "  --idle-color: #faa61a;"
    "  --dnd-color: #982929;"
    "  --streaming-color: #593695;"
    "  --offline-color: #808080;"
    "  --background-shading-percent: 100%;"
    "  --background-image: url(\"https://4noy.github.io/discord-wallpaper.jpg\");"
    "  --background-position: center;"
    "  --background-size: cover;"
    "  --background-attachment: fixed;"
    "  --background-filter: saturate(calc(var(--saturation-factor,1)*1));"
    "  --user-popout-image: var(--background-image);"
    "  --user-modal-image: var(--background-image);"
    "  --home-icon: url(https://clearvision.github.io/icons/discord.svg);"
    "  --home-size: cover;"
    "  --main-font: \"gg sans\",\"Helvetica Neue\",Helvetica,Arial,sans-serif;"
    "  --code-font: Consolas,\"gg mono\",\"Liberation Mono\",Menlo,Courier,monospace;"
    "}"
    "/* theme light */"
    ":is(.theme-light,.theme-dark .theme-light){"
    "  --background-shading:rgba(252,252,252,0.3);"
    "  --card-shading:rgba(252,252,252,0.3);"
    "  --popout-shading:rgba(252,252,252,0.7);"
    "  --modal-shading:rgba(252,252,252,0.5);"
    "  --input-shading:rgba(0,0,0,0.3);"
    "  --normal-text:#36363c;"
    "  --muted-text:#75757e;"
    "}"
    "/* theme dark */"
    ":is(.theme-dark,.theme-light .theme-dark){"
    "  --background-shading:rgba(0,0,0,0.4);"
    "  --card-shading:rgba(0,0,0,0.2);"
    "  --popout-shading:rgba(0,0,0,0.6);"
    "  --modal-shading:rgba(0,0,0,0.4);"
    "  --input-shading:rgba(255,255,255,0.05);"
    "  --normal-text:#d8d8db;"
    "  --muted-text:#aeaeb4;"
    "}"
    "/* theme darker */"
    ":is(.theme-darker,.theme-light .theme-darker){"
    "  --background-shading:rgba(0,0,0,0.6);"
    "  --card-shading:rgba(0,0,0,0.3);"
    "  --popout-shading:rgba(0,0,0,0.7);"
    "  --modal-shading:rgba(0,0,0,0.5);"
    "  --input-shading:rgba(255,255,255,0.05);"
    "  --normal-text:#fbfbfb;"
    "  --muted-text:#94949c;"
    "}"
    "/* theme midnight */"
    ":is(.theme-midnight,.theme-light .theme-midnight){"
    "  --background-shading:rgba(0,0,0,0.8);"
    "  --card-shading:rgba(0,0,0,0.4);"
    "  --popout-shading:rgba(0,0,0,0.8);"
    "  --modal-shading:rgba(0,0,0,0.6);"
    "  --input-shading:rgba(255,255,255,0.05);"
    "  --normal-text:#dcdcde;"
    "  --muted-text:#86868e;"
    "}"
  ];
in {
  home.packages = [ discordPkg ];

  home.file."${destDir}/discord-wallpaper.jpg".source = wallSrc;

  home.file."${destDir}/${themeName}".text = cssLines;
}
